### ISSUE TITLE
Pandas Timestamps and filtering

### ISSUE THREAD

**Issue by eternalscholar** [NCSU-Libraries/data-science-cookbook#7]
Here is a Colab notebook for timestamp-based filtering of Pandas data frames. The code includes converting specific columns in pandas data frame to "datetime" type. This is a code snippet that I used to help a patron last semester.

Colab Notebook: [https://colab.research.google.com/drive/1L-3vUhsFkKmUYrDhJJAuV3Uh1o56uHRZ?usp=sharing](https://colab.research.google.com/drive/1L-3vUhsFkKmUYrDhJJAuV3Uh1o56uHRZ?usp=sharing)
Data: [https://drive.google.com/drive/folders/1oWS1yut249Ur_F5i5pcGcwm6Fd4UtEWf?usp=sharing](https://drive.google.com/drive/folders/1oWS1yut249Ur_F5i5pcGcwm6Fd4UtEWf?usp=sharing)

**Comment by mikenutt** [comment]
Thanks for this @eternalscholar! Could you create a branch for this Notebook? I'd also like code for the cookbook to be written in a "literate programming" style with human-readable text that describes what's happening in the code. Here's an example that might be interesting to you: https://github.com/datadesk/vr-interactives-three-js. We might also want to copy the sample data to the repository so that it doesn't depend on your Google Drive link.
